//////////////////////////////
// Autogenerated with nxc2cc
//

#include "nxclib.h"

pthread_t __thr_main;
void * __task_main(void *arg);
bool __spawned_main = false;

uint32_t CurrentTick_();
uint32_t FirstTick_();
void Wait__ulong(uint32_t ms);
void Yield_();
void StopAllTasks_();
void Stop__bool(bool really);
void Acquire__mutex(pthread_mutex_t (*m));
void Release__mutex(pthread_mutex_t (*m));
void SetLedWarning__bool(bool Value);
uint8_t LedWarning_();
void SetLedPattern__ubyte(uint8_t Pattern);
uint8_t LedPattern_();
uint16_t ButtonWaitForAnyEvent__uint(uint16_t timeout);
uint16_t ButtonWaitForAnyPress__uint(uint16_t timeout);
bool ButtonIsUp__ubyte(uint8_t Button);
bool ButtonIsDown__ubyte(uint8_t Button);
void ButtonWaitForPress__ubyte(uint8_t Button);
void ButtonWaitForPressAndRelease__ubyte(uint8_t Button);
bool ButtonPressed__ubyte_bool(uint8_t btn, bool resetCount);
bool ButtonPressed__ubyte(uint8_t btn){
  bool resetCount = false;
  return ButtonPressed__ubyte_bool(btn,resetCount);
}
int8_t ReadButtonEx__ubyte_bool_bool_uint(uint8_t btn, bool reset, bool (*pressed), uint16_t (*count));
uint8_t ButtonState__ubyte(uint8_t btn);
struct LocationType ;
void ResetScreen_();
void ClearScreen_();
void printf__string_slong(char * format, int32_t value);
void printf__string_float(char * format, float value);
void printf__string_string(char * format, char * value);
int8_t CircleOut__sint_sint_ubyte_ulong(int16_t x, int16_t y, uint8_t radius, uint32_t options);
int8_t CircleOut__sint_sint_ubyte(int16_t x, int16_t y, uint8_t radius){
  uint32_t options = 0x0000;
  return CircleOut__sint_sint_ubyte_ulong(x,y,radius,options);
}
int8_t LineOut__sint_sint_sint_sint_ulong(int16_t x1, int16_t y1, int16_t x2, int16_t y2, uint32_t options);
int8_t LineOut__sint_sint_sint_sint(int16_t x1, int16_t y1, int16_t x2, int16_t y2){
  uint32_t options = 0x0000;
  return LineOut__sint_sint_sint_sint_ulong(x1,y1,x2,y2,options);
}
int8_t PointOut__sint_sint_ulong(int16_t x, int16_t y, uint32_t options);
int8_t PointOut__sint_sint(int16_t x, int16_t y){
  uint32_t options = 0x0000;
  return PointOut__sint_sint_ulong(x,y,options);
}
int8_t RectOut__sint_sint_sint_sint_ulong(int16_t x, int16_t y, int16_t width, int16_t height, uint32_t options);
int8_t RectOut__sint_sint_sint_sint(int16_t x, int16_t y, int16_t width, int16_t height){
  uint32_t options = 0x0000;
  return RectOut__sint_sint_sint_sint_ulong(x,y,width,height,options);
}
int8_t TextOut__sint_sint_string_ulong(int16_t x, int16_t y, char * str, uint32_t options);
int8_t TextOut__sint_sint_string(int16_t x, int16_t y, char * str){
  uint32_t options = 0x0000;
  return TextOut__sint_sint_string_ulong(x,y,str,options);
}
int8_t NumOut__sint_sint_sint_ulong(int16_t x, int16_t y, int16_t value, uint32_t options);
int8_t NumOut__sint_sint_sint(int16_t x, int16_t y, int16_t value){
  uint32_t options = 0x0000;
  return NumOut__sint_sint_sint_ulong(x,y,value,options);
}
int8_t EllipseOut__sint_sint_ubyte_ubyte_ulong(int16_t x, int16_t y, uint8_t radiusX, uint8_t radiusY, uint32_t options);
int8_t EllipseOut__sint_sint_ubyte_ubyte(int16_t x, int16_t y, uint8_t radiusX, uint8_t radiusY){
  uint32_t options = 0x0000;
  return EllipseOut__sint_sint_ubyte_ubyte_ulong(x,y,radiusX,radiusY,options);
}
int8_t PolyOut__arr1type26_ulong(struct LocationType* points, uint32_t options);
int8_t PolyOut__arr1type26(struct LocationType* points){
  uint32_t options = 0x0000;
  return PolyOut__arr1type26_ulong(points,options);
}
int8_t GraphicOut__sint_sint_string_ulong(int16_t x, int16_t y, char * filename, uint32_t options);
int8_t GraphicOut__sint_sint_string(int16_t x, int16_t y, char * filename){
  uint32_t options = 0x0000;
  return GraphicOut__sint_sint_string_ulong(x,y,filename,options);
}
int8_t GraphicArrayOut__sint_sint_arr1ubyte_ulong(int16_t x, int16_t y, uint8_t* data, uint32_t options);
int8_t GraphicArrayOut__sint_sint_arr1ubyte(int16_t x, int16_t y, uint8_t* data){
  uint32_t options = 0x0000;
  return GraphicArrayOut__sint_sint_arr1ubyte_ulong(x,y,data,options);
}
void OffEx__ubyte_cubyte(uint8_t outputs, const uint8_t reset);
void FloatEx__ubyte_cubyte(uint8_t outputs, const uint8_t reset);
void CoastEx__ubyte_cubyte(uint8_t outputs, const uint8_t reset);
void OnFwdEx__ubyte_sbyte_cubyte(uint8_t outputs, int8_t pwr, const uint8_t reset);
void OnRevEx__ubyte_sbyte_cubyte(uint8_t outputs, int8_t pwr, const uint8_t reset);
void OnFwdRegEx__ubyte_sbyte_ubyte_cubyte(uint8_t outputs, int8_t pwr, uint8_t regmode, const uint8_t reset);
void OnRevRegEx__ubyte_sbyte_ubyte_cubyte(uint8_t outputs, int8_t pwr, uint8_t regmode, const uint8_t reset);
void OnFwdSyncEx__ubyte_sbyte_sbyte_cubyte(uint8_t outputs, int8_t pwr, int8_t turnpct, const uint8_t reset);
void OnRevSyncEx__ubyte_sbyte_sbyte_cubyte(uint8_t outputs, int8_t pwr, int8_t turnpct, const uint8_t reset);
void RotateMotorEx__ubyte_sbyte_slong_sint_bool_bool(uint8_t outputs, int8_t pwr, int32_t angle, int16_t turnpct, bool sync, bool stop_);
void ResetTachoCount__ubyte(uint8_t outputs);
void ResetBlockTachoCount__ubyte(uint8_t outputs);
void ResetRotationCount__ubyte(uint8_t outputs);
void ResetAllTachoCounts__ubyte(uint8_t outputs);
void ResetCount__ubyte_ubyte(uint8_t Outputs, uint8_t reset);
int8_t MotorPower__ubyte(uint8_t output);
int8_t MotorActualSpeed__ubyte(uint8_t output);
int32_t MotorTachoCount__ubyte(uint8_t output);
int32_t MotorBlockTachoCount__ubyte(uint8_t output);
int32_t MotorRotationCount__ubyte(uint8_t output);
bool MotorBusy__ubyte(uint8_t Output);
void RotateMotorRampNoWait__ubyte_sbyte_sint_sint_sint_bool(uint8_t Outputs, int8_t Speed, int16_t accelAngle, int16_t steadyAngle, int16_t decelAngle, bool Stop);
void RotateMotorRamp__ubyte_sbyte_sint_sint_sint_bool(uint8_t Outputs, int8_t Speed, int16_t accelAngle, int16_t steadyAngle, int16_t decelAngle, bool Stop);
void Off__ubyte(uint8_t outputs){
  OffEx__ubyte_cubyte(outputs,0x28);
}
void Coast__ubyte(uint8_t outputs){
  CoastEx__ubyte_cubyte(outputs,0x28);
}
void Float__ubyte(uint8_t outputs){
  FloatEx__ubyte_cubyte(outputs,0x28);
}
void OnFwd__ubyte_sbyte(uint8_t outputs, int8_t pwr){
  OnFwdEx__ubyte_sbyte_cubyte(outputs,pwr,0x28);
}
void OnRev__ubyte_sbyte(uint8_t outputs, int8_t pwr){
  OnRevEx__ubyte_sbyte_cubyte(outputs,pwr,0x28);
}
void OnFwdReg__ubyte_sbyte_ubyte(uint8_t outputs, int8_t pwr, uint8_t regmode){
  OnFwdRegEx__ubyte_sbyte_ubyte_cubyte(outputs,pwr,regmode,0x28);
}
void OnRevReg__ubyte_sbyte_ubyte(uint8_t outputs, int8_t pwr, uint8_t regmode){
  OnRevRegEx__ubyte_sbyte_ubyte_cubyte(outputs,pwr,regmode,0x28);
}
void OnFwdSync__ubyte_sbyte_sbyte(uint8_t outputs, int8_t pwr, int8_t turnpct){
  OnFwdSyncEx__ubyte_sbyte_sbyte_cubyte(outputs,pwr,turnpct,0x28);
}
void OnRevSync__ubyte_sbyte_sbyte(uint8_t outputs, int8_t pwr, int8_t turnpct){
  OnRevSyncEx__ubyte_sbyte_sbyte_cubyte(outputs,pwr,turnpct,0x28);
}
void RotateMotor__ubyte_sbyte_slong(uint8_t outputs, int8_t pwr, int32_t angle){
  RotateMotorEx__ubyte_sbyte_slong_sint_bool_bool(outputs,pwr,angle,0,true,true);
}
int8_t PlayFile__string(char * filename);
int8_t PlayFileEx__string_ubyte_bool_uint(char * filename, uint8_t volume, bool loop, uint16_t sr);
int8_t PlayFileEx__string_ubyte_bool(char * filename, uint8_t volume, bool loop){
  uint16_t sr = 0;
  return PlayFileEx__string_ubyte_bool_uint(filename,volume,loop,sr);
}
int8_t PlayTone__uint_uint(uint16_t frequency, uint16_t duration);
int8_t PlayToneEx__uint_uint_ubyte_bool(uint16_t frequency, uint16_t duration, uint8_t volume, bool loop);
uint8_t SoundState_();
uint8_t StopSound_();
uint8_t SensorUS__ubyte(uint8_t port);
void SetSensorType__ubyte_ubyte(uint8_t port, uint8_t type);
void ClearSensor__ubyte(uint8_t port);
void ResetSensor__ubyte(uint8_t port);
void SetSensor__ubyte_cuint(uint8_t port, const uint16_t config);
void SetSensorTouch__ubyte(uint8_t port);
void SetSensorLight__ubyte_bool(uint8_t port, bool bActive);
void SetSensorLight__ubyte(uint8_t port){
  bool bActive = true;
  return SetSensorLight__ubyte_bool(port,bActive);
}
void SetSensorSound__ubyte_bool(uint8_t port, bool bdBScaling);
void SetSensorSound__ubyte(uint8_t port){
  bool bdBScaling = true;
  return SetSensorSound__ubyte_bool(port,bdBScaling);
}
void SetSensorLowspeed__ubyte_bool(uint8_t port, bool bIsPowered);
void SetSensorLowspeed__ubyte(uint8_t port){
  bool bIsPowered = true;
  return SetSensorLowspeed__ubyte_bool(port,bIsPowered);
}
void SetSensorUltrasonic__ubyte(uint8_t port);
void SetSensorUltrasonicMM__ubyte(uint8_t port);
void SetSensorColorFull__ubyte(uint8_t port);
void SetSensorColorRed__ubyte(uint8_t port);
void SetSensorColorGreen__ubyte(uint8_t port);
void SetSensorColorBlue__ubyte(uint8_t port);
void SetSensorColorNone__ubyte(uint8_t port);
void SetSensorHTGyro__ubyte(uint8_t port);
int16_t SensorHTGyro__ubyte_sint(uint8_t port, int16_t offset);
int16_t SensorHTGyro__ubyte(uint8_t port){
  int16_t offset = 0;
  return SensorHTGyro__ubyte_sint(port,offset);
}
float GetInput__ubyte_cubyte(uint8_t port, const uint8_t field);
uint16_t Sensor__ubyte(uint8_t port);
bool SensorInvalid__ubyte(uint8_t port);
uint8_t SensorMode__ubyte(uint8_t port);
uint16_t SensorNormalized__ubyte(uint8_t port);
uint16_t SensorRaw__ubyte(uint8_t port);
uint16_t SensorScaled__ubyte(uint8_t port);
uint8_t SensorType__ubyte(uint8_t port);
uint16_t SensorValue__ubyte(uint8_t port);
uint16_t SensorValueRaw__ubyte(uint8_t port);
int16_t Random__uint(uint16_t n);
int16_t Random_(){
  uint16_t n = 0;
  return Random__uint(n);
}
void *__task_main_real(PRECEDES_ARGS)
{
  TextOut__sint_sint_string(0,0,"hello world");
  Wait__ulong(1000);
}

void *__task_main(void *arg) {
  __spawned_main = true;
  PRECEDES_INIT;
  PRECEDES_CALL(__task_main_real);
  PRECEDES_EXEC;
  PRECEDES_FREE;
}

// Autogenerated entrypoint: initialize global mutexes + spawn main thread
void entrypoint() {
  pthread_mutexattr_t attrs;
  pthread_mutexattr_init(&attrs);
  pthread_mutexattr_settype(&attrs, PTHREAD_MUTEX_RECURSIVE);


  pthread_mutexattr_destroy(&attrs);

  thread_start(&__thr_main, __task_main);
}
